### ISSUE TITLE
Create Login page

### ISSUE THREAD

**Issue by supriyasinhaa** [supriyasinhaa/Basic-Login-Page#3]
Create a Login Page with unique designs

**Comment by Uyadav207** [comment]
@supriyasinhaa , Please assign it to me.

**Comment by pavanjoshi914** [comment]
HII I would like to work on this 
do we need changes to exisiting repo or want a whole new login page with new design
~thanks

**Comment by supriyasinhaa** [comment]
Make a new Login Page by creating a separate folder with Login-Page-2

**Comment by symtalha14** [comment]
Hello, 
Even I would like to create a new login page which would be minimalistic and fast to load. May I initiate a PR after doing that?

**Comment by ashikvarma11** [comment]
@supriyasinhaa I would like to build Login-Page-3.

**Comment by supriyasinhaa** [comment]
Yes, just comment here and make a PR of your work done.

**Comment by priyankaagrawal123** [comment]
I am interested. I can implement.
Please assign this issue to me.

**Comment by symtalha14** [comment]
Please assign this issue to me.

**Comment by snic82** [comment]
I would like to contribute
