### ISSUE TITLE
Update the readme file

### ISSUE THREAD

**Issue by supriyasinhaa** [supriyasinhaa/Basic-Login-Page#4]

**Comment by GSantos23** [comment]
Can I have this one?

**Comment by Lilykhan786** [comment]
Can I help?

**Comment by supriyasinhaa** [comment]
Yes. Take this issue and work on it.

**Comment by priyankaagrawal123** [comment]
I am interested. I can implement.
Please assign this issue to me

**Comment by meghasharma123** [comment]
Can I work on this issue?

**Comment by priyankaagrawal123** [comment]
Hello ,can I try this issue

**Comment by supriyasinhaa** [comment]
Yes, Those who wants to work on this issue comment here and make a PR.

**Comment by kkkkkabir** [comment]
I am interested to work on this issue.

**Comment by symtalha14** [comment]
I want to work on this. Please Assign me this issue.
